package org.bigBrotherBooks.configModels;

public enum Genre {
    FICTION, NON_FICTION, SCIENCE_FICTION, MYSTERY, THRILLER, ROMANCE, HORROR, BIOGRAPHY, AUTOBIOGRAPHY, HISTORY, SCIENCE, PHILOSOPHY, SELF_HELP, TRAVEL, GUIDE, CHILDREN, YOUNG_ADULT, COMICS, FANTASY, CLASSICS, POETRY, DRAMA, SHORT_STORIES, ESSAYS, CRIME, ADVENTURE, MYTHOLOGY, RELIGION, SPIRITUALITY, POLITICS, SOCIOLOGY, PSYCHOLOGY, ECONOMICS, BUSINESS, MANAGEMENT, MARKETING, FINANCE, ACCOUNTING, LAW, MEDICINE, HEALTH, FITNESS, COOKBOOK, FOOD, DRINK, ART, MUSIC, FILM, PHOTOGRAPHY, DESIGN, CRAFT, HOBBY, SPORTS, GAMES, COMPUTERS, TECHNOLOGY, ENGINEERING, MATHEMATICS, ARCHITECTURE, LITERATURE, LANGUAGE, EDUCATION, PARENTING, FAMILY, RELATIONSHIPS, GARDENING, HOME, DIY, FASHION, BEAUTY, LIFESTYLE, HUMOR, COMEDY, SATIRE, CRITICISM, JOURNALISM, MEMOIR, NATURE, ENVIRONMENT

}
